version: "3.0"

networks:
  etcd-net:
    driver: bridge

services:
  myetcd1:
    image: bitnami/etcd:3.4.13-debian-10-r0
    container_name: myetcd1
    restart: always
    networks:
      - etcd-net
    ports:
      - "23791:2379"
      - "23801:2380"
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
      - ETCD_NAME=myetcd1
      - ETCD_LISTEN_PEER_URLS=http://0.0.0.0:2380
      - ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379
      - ETCD_INITIAL_ADVERTISE_PEER_URLS=http://myetcd1:2380
      - ETCD_ADVERTISE_CLIENT_URLS=http://myetcd1:2379
      - ETCD_INITIAL_CLUSTER_TOKEN=etcd-cluster
      - ETCD_INITIAL_CLUSTER=myetcd1=http://myetcd1:2380,myetcd2=http://myetcd2:2380,myetcd3=http://myetcd3:2380,myetcd4=http://myetcd4:2380
      - ETCD_INITIAL_CLUSTER_STATE=new
    volumes:
      - ./etcddata/etcddata1:/bitnami/etcd

  myetcd2:
    image: bitnami/etcd:3.4.13-debian-10-r0
    container_name: myetcd2
    restart: always
    networks:
      - etcd-net
    ports:
      - "23792:2379"
      - "23802:2380"
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
      - ETCD_NAME=myetcd2
      - ETCD_LISTEN_PEER_URLS=http://0.0.0.0:2380
      - ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379
      - ETCD_INITIAL_ADVERTISE_PEER_URLS=http://myetcd2:2380
      - ETCD_ADVERTISE_CLIENT_URLS=http://myetcd2:2379
      - ETCD_INITIAL_CLUSTER_TOKEN=etcd-cluster
      - ETCD_INITIAL_CLUSTER=myetcd1=http://myetcd1:2380,myetcd2=http://myetcd2:2380,myetcd3=http://myetcd3:2380,myetcd4=http://myetcd4:2380
      - ETCD_INITIAL_CLUSTER_STATE=new
    volumes:
      - ./etcddata/etcddata2:/bitnami/etcd

  myetcd3:
    image: bitnami/etcd:3.4.13-debian-10-r0
    container_name: myetcd3
    restart: always
    networks:
      - etcd-net
    ports:
      - "23793:2379"
      - "23803:2380"
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
      - ETCD_NAME=myetcd3
      - ETCD_LISTEN_PEER_URLS=http://0.0.0.0:2380
      - ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379
      - ETCD_INITIAL_ADVERTISE_PEER_URLS=http://myetcd3:2380
      - ETCD_ADVERTISE_CLIENT_URLS=http://myetcd3:2379
      - ETCD_INITIAL_CLUSTER_TOKEN=etcd-cluster
      - ETCD_INITIAL_CLUSTER=myetcd1=http://myetcd1:2380,myetcd2=http://myetcd2:2380,myetcd3=http://myetcd3:2380,myetcd4=http://myetcd4:2380
      - ETCD_INITIAL_CLUSTER_STATE=new
    volumes:
      - ./etcddata/etcddata3:/bitnami/etcd

  myetcd4:
    image: bitnami/etcd:3.4.13-debian-10-r0
    container_name: myetcd4
    restart: always
    networks:
      - etcd-net
    ports:
      - "23794:2379"
      - "23804:2380"
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
      - ETCD_NAME=myetcd4
      - ETCD_LISTEN_PEER_URLS=http://0.0.0.0:2380
      - ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379
      - ETCD_INITIAL_ADVERTISE_PEER_URLS=http://myetcd4:2380
      - ETCD_ADVERTISE_CLIENT_URLS=http://myetcd4:2379
      - ETCD_INITIAL_CLUSTER_TOKEN=etcd-cluster
      - ETCD_INITIAL_CLUSTER=myetcd1=http://myetcd1:2380,myetcd2=http://myetcd2:2380,myetcd3=http://myetcd3:2380,myetcd4=http://myetcd4:2380
      - ETCD_INITIAL_CLUSTER_STATE=new
    volumes:
      - ./etcddata/etcddata4:/bitnami/etcd